name: Auto Commit Workflow

on:
  schedule:
    # Menjalankan workflow setiap hari pada jam 00:00 UTC
    - cron: "0 0 * * *"

  workflow_dispatch:
    # Menjalankan workflow secara manual (opsional)
    inputs:
      min_commits:
        description: "Jumlah commit minimum"
        required: false
        default: "100" # Input harus string
      max_commits:
        description: "Jumlah commit maksimum"
        required: false
        default: "200" # Input harus string

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
    # Checkout repository
    - name: Checkout Repository
      uses: actions/checkout@v3

    # Setup Git Configuration
    - name: Setup Git Configuration
      run: |
        git config user.email "njolchipz@gmail.com"
        git config user.name "AfifAljav"

    # Setup Python environment
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    # Install dependencies
    - name: Install Dependencies
      run: python -m pip install python-dotenv

    # Run the script
    - name: Run Auto Commit Script
      env:
        MIN_COMMITS: ${{ inputs.min_commits }}
        MAX_COMMITS: ${{ inputs.max_commits }}
      run: python scripts/auto_commit.py

    # Push changes back to repository
    - name: Push Changes
      run: git push
